sudo: false
branches:
  only:
  - develop
language: ruby
rvm:
- 2.2.0
before_install:
- bash ./start.bash
install:
- travis_retry gem install jekyll -v '2.4.0'
- travis_retry gem install kramdown -v 1.7.0
- travis_retry gem install jekyll-sitemap
- travis_retry npm install -g grunt
- travis_retry npm install -g bower
- travis_retry npm install -g grunt-cli
before_script:
- npm install
- bower install
script:
- grunt ci
- grunt build
after_success:
- coveralls
- bash ./script.bash
notifications:
  email: rapha.fabeni@gmail.com
env:
  global:
    secure: mQD7tw5fQCMvcx3Tt2oM54dtnXL67CdFBSd12/82b66k94YLhRfnuyFKjS7avAovsGR95H9ZZ+Ix+sWMSjuzfu50Xrk1Bo8CL/aUqIphtK0C7wM4oGSUXFTYwcRTQZzYx3CcsH31roK8ViSVG8cLBJb0aJyYm/E7CuE/qqS725s=
