---
title: Raphael Fabeni
name: Raphael Fabeni
email: rapha.fabeni@gmail.com
description: A brazilian front-end developer who loves the web, electronic music and
  travels.
baseurl: ''
url: https://www.raphaelfabeni.com
exclude:
- node_modules
- package.json
- bin
- README.md
- script.bash
- Gemfile.lock
- Gemfile
- start.bash
- src
permalink: "/:title/"
markdown: kramdown
kramdown:
  input: GFM
source: "."
destination: "./_site"
plugins:
- jekyll-gist
- octopress-debugger
- jekyll-sitemap
blog:
  en: "/blog/"
  pt-br: "/pt-br/blog/"
collections:
  category:
    output: true
gist:
  noscript: false
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
